from __future__ import annotations

ENTITY_BANK = {
    "PER": [
        "John Smith",
        "Emma Wilson",
        "Michael Brown",
        "Sophia Davis",
        "David Miller",
        "Olivia Taylor",
        "James Anderson",
        "Isabella Thomas",
        "William Jackson",
        "Mia White",
        "Barack Obama",
        "Angela Merkel",
        "Sundar Pichai",
        "Elon Musk",
        "Satya Nadella",
    ],
    "ORG": [
        "Google",
        "Microsoft",
        "OpenAI",
        "Amazon",
        "Apple",
        "Meta",
        "Tesla",
        "Stanford University",
        "United Nations",
        "World Bank",
        "BBC",
        "Reuters",
        "Harvard University",
        "NATO",
        "Infosys",
    ],
    "LOC": [
        "Paris",
        "London",
        "New York",
        "California",
        "Berlin",
        "Tokyo",
        "Delhi",
        "Mumbai",
        "Sydney",
        "Toronto",
        "Seattle",
        "San Francisco",
        "Singapore",
        "Dubai",
        "Geneva",
    ],
    "MISC": [
        "Olympics",
        "English",
        "iPhone",
        "Nobel Prize",
        "World Cup",
        "Monday",
        "Christmas",
        "Tesla Model S",
        "Python",
        "Linux",
        "Euro 2024",
        "ChatGPT",
        "Mars Mission",
        "Formula One",
        "Bitcoin",
    ],
}
